Add docker-compose v1 and v2

diff --git a/build b/build
--- a/build
+++ b/build
@@ -29,9 +29,11 @@ if ! command -v jq ; then
   exit 1
 fi
 
-set -x
-
 . ./dockerhub-userdata
+
+echo '+ . ./dockerhub-userdata'
+
+set -x
 
 if test "${RUN_PUSH:-n}" = "y" ; then
   # I predict that accepting password as an argument will eventually be deprecated
@@ -50,25 +52,45 @@ jenkinsNameSuffix="${JENKINS_NAME_SUFFIX:-jdk11}"
 #cat /etc/localtime > .auto-gen/localtime
 #cat /etc/timezone > .auto-gen/timezone
 #docker build --no-rm --build-arg TARGETARCH=amd64 -f Dockerfile -t local/docker_jenkins:alpine3.15 .
-latestDockerVersion="$(curl https://download.docker.com/linux/static/stable/x86_64/ | grep -oE 'docker-[0-9]*[.][0-9]*[.][0-9]*[.]tgz' | sort -rh | grep -m1 -oE '[0-9]*[.][0-9]*[.][0-9]*')"
+
+printf '\n\n\e[0;32mGathering the latest version of docker...\e(B\e[m\n'
+latestDockerVersion="$(curl -sSL 'https://download.docker.com/linux/static/stable/x86_64/' | grep -oE 'docker-[0-9][0-9]*[.][0-9][0-9]*[.][0-9][0-9]*[.]tgz' | sort -rh | grep -m1 -oE '[0-9][0-9]*[.][0-9][0-9]*[.][0-9][0-9]*')"
+if test -z "$latestDockerVersion" ; then
+  echo 'ERR: Could not gather what the latest version of docker is!'
+  exit 1
+fi
+
+printf '\n\n\e[0;32mGathering the latest version of docker-compose...\e(B\e[m\n'
+latestComposeVersion="$(curl -sSL 'https://api.github.com/repos/docker/compose/releases/latest' | jq -r ".tag_name")"
+if test -z "$latestComposeVersion" ; then
+  echo 'ERR: Could not gather what the latest version of docker-compose is!'
+  exit 1
+fi
+
+# needed for some tests and tagging. The "cut" is to get rid of the "v". If latestComposeVersion=v1.2.3 then cutComposeVersion=1.2.3
+export cutComposeVersion
+cutComposeVersion="$( echo "$latestComposeVersion" | cut -c2- )"
+
 
 if test "${RUN_BUILD:-y}" = "y" ; then
-  docker build --build-arg "DOCKER_VERSION=$latestDockerVersion" --build-arg "JENKINS_BASE_IMAGE=$jenkinsBaseImage" -f docker-resources/Dockerfile -t local/docker-jenkins-alpine docker-resources
+  printf '\n\n\e[0;32mNow building...\e(B\e[m\n'
+  docker build --build-arg "DOCKER_VERSION=$latestDockerVersion" --build-arg "JENKINS_BASE_IMAGE=$jenkinsBaseImage" --build-arg "DOCKER_COMPOSE_VERSION=$latestComposeVersion" -f docker-resources/Dockerfile -t local/docker-jenkins-alpine docker-resources
 
-  printf "\n\n\e[0;32mBuild was successful\e(B\e[m\n"
+  printf '\n\n\e[0;32mBuild was successful\e(B\e[m\n'
 else
   echo 'Build was skipped.'
 fi
 
 if test "${RUN_TESTS:-y}" = "y" ; then
-  containerId="$( docker run --rm --detach --privileged --env DEBUG_KILLAFTER_SEC=180 --cpuset-cpus=1,3,5,7 --cpu-period=10000 local/docker-jenkins-alpine )"
+  printf '\n\n\e[0;32mNow testing...\e(B\e[m\n'
+  containerId="$( docker run --rm --detach --privileged --env "DEBUG_KILLAFTER_SEC=${DEBUG_KILLAFTER_SEC:-180}" --cpuset-cpus=1,3,5,7 --cpu-period=10000 local/docker-jenkins-alpine )"
 
   # if it can't boot up in under a minute, then something is seriously wrong
-  sleep 60
+  sleep ${BUILD_SLEEP_SEC:-60}
 
   for test in ./tests/*
   do
-    echo -e '\e[0;32m> Running test '"$test"'\e(B\e[m'
+    printf '\n\e[0;32m> Running test %s\e(B\e[m\n' "$test"
     $test "$containerId"
   done
 
@@ -93,8 +115,13 @@ if ! test "${RUN_PUSH:-n}" = "y" ; then
   exit 0
 fi
 
+printf '\n\n\e[0;32mNow pushing up online...\e(B\e[m\n'
+
 dockerMinorVersion="${latestDockerVersion%.*}"
 dockerMajorVersion="${dockerMinorVersion%.*}"
+
+composeMinorVersion="${cutComposeVersion%.*}"
+composeMajorVersion="${composeMinorVersion%.*}"
 
 jenkinsRevisionVersion="$(docker inspect local/docker-jenkins-alpine | jq -r '.[0].ContainerConfig.Labels."org.opencontainers.image.version"')"
 jenkinsMinorVersion="${jenkinsRevisionVersion%.*}"
@@ -131,23 +158,30 @@ tagAndPushAndRmImage() (
   echoback docker image rm "$1"
 )
 
-for dockVer in ',' "docker$latestDockerVersion-" "docker$dockerMinorVersion-" "docker$dockerMajorVersion-"
+for compVer in ',' "compose$cutComposeVersion-" "compose$composeMinorVersion-" "compose$composeMajorVersion-"
 do
-  if test -z "$dockVer" ; then
+  if test -z "$compVer" ; then
     # sanity check
     continue
   fi
-  for jenkVer in ',' "jenkins$jenkinsRevisionVersion-" "jenkins$jenkinsMinorVersion-" "jenkins$jenkinsMajorVersion-"
+  for dockVer in ',' "docker$latestDockerVersion-" "docker$dockerMinorVersion-" "docker$dockerMajorVersion-"
   do
-    if test -z "$jenkVer" ; then
+    if test -z "$dockVer" ; then
       # sanity check
       continue
     fi
-    
-    nextTag="$REPOPREFIX/docker-jenkins-alpine:${dockVer%,}${jenkVer%,}$jenkinsNameSuffix"
-    echo "STATUS: aliasing $nextTag -> local/docker-jenkins-alpine"
-    
-    tagAndPushAndRmImage "$nextTag"
+    for jenkVer in ',' "jenkins$jenkinsRevisionVersion-" "jenkins$jenkinsMinorVersion-" "jenkins$jenkinsMajorVersion-"
+    do
+      if test -z "$jenkVer" ; then
+        # sanity check
+        continue
+      fi
+      
+      nextTag="$REPOPREFIX/docker-jenkins-alpine:${compVer%,}${dockVer%,}${jenkVer%,}$jenkinsNameSuffix"
+      echo "STATUS: aliasing $nextTag -> local/docker-jenkins-alpine"
+      
+      tagAndPushAndRmImage "$nextTag"
+    done
   done
 done
 
